SOURCE_TYPE_DOCUMENT = "document"
SOURCE_TYPE_KNOWLEDGE_OBJECT = "knowledge_object"
SOURCE_TYPE_INCIDENT = "incident"

CHUNK_STATUS_ACTIVE = "active"
CHUNK_STATUS_ARCHIVED = "archived"
CHUNK_STATUS_EXCLUDED = "excluded"

CHUNK_SIZE = 1500
CHUNK_OVERLAP = 150
