"""add document title

Revision ID: 18a4b4d8f4d5
Revises: faaebe060a6b
Create Date: 2026-06-03 18:50:29.955947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a4b4d8f4d5'
down_revision: Union[str, None] = 'faaebe060a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column(
        'document_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'document_title')
    # ### end Alembic commands ###
