"""users_table

Revision ID: 6193f4e2b927
Revises: 001
Create Date: 2026-06-03 10:25:39.491681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '6193f4e2b927'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('tenants',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('slug', sa.String(length=120), nullable=False),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    op.create_table('knowledge_chunks',
                    sa.Column('site_ids', postgresql.ARRAY(
                        sa.UUID()), nullable=True),
                    sa.Column('source_type', sa.String(
                        length=64), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=False),
                    sa.Column('chunk_text', sa.Text(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1024), nullable=True),
                    sa.Column('topic', sa.String(length=255), nullable=True),
                    sa.Column('task_type', sa.String(
                        length=128), nullable=True),
                    sa.Column('asset_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('source_scope', sa.String(
                        length=32), nullable=True),
                    sa.Column('risk_level', sa.String(
                        length=32), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('page_number', sa.Integer(), nullable=True),
                    sa.Column('section_title', sa.String(
                        length=255), nullable=True),
                    sa.Column('confidence_score', sa.Numeric(
                        precision=4, scale=3), nullable=True),
                    sa.Column('celery_task_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', [
                    'embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_chunks_risk_level',
                    'knowledge_chunks', ['risk_level'], unique=False)
    op.create_index('ix_knowledge_chunks_source_id',
                    'knowledge_chunks', ['source_id'], unique=False)
    op.create_index('ix_knowledge_chunks_source_scope',
                    'knowledge_chunks', ['source_scope'], unique=False)
    op.create_index('ix_knowledge_chunks_source_type',
                    'knowledge_chunks', ['source_type'], unique=False)
    op.create_index('ix_knowledge_chunks_status',
                    'knowledge_chunks', ['status'], unique=False)
    op.create_index('ix_knowledge_chunks_task_type',
                    'knowledge_chunks', ['task_type'], unique=False)
    op.create_index('ix_knowledge_chunks_topic',
                    'knowledge_chunks', ['topic'], unique=False)
    op.create_table('sites',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('code', sa.String(length=64), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tenant_id', 'name',
                                        name='uq_sites_tenant_id_name')
                    )
    op.create_index('ix_sites_tenant_id', 'sites', ['tenant_id'], unique=False)
    op.create_table('users',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=64), nullable=False),
                    sa.Column('password', sa.String(
                        length=128), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('last_login_at', sa.DateTime(), nullable=True),
                    sa.Column('role_id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['roles.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('documents',
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('file_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('file_url', sa.Text(), nullable=False),
                    sa.Column('file_type', sa.String(
                        length=128), nullable=True),
                    sa.Column('file_size_bytes',
                              sa.BigInteger(), nullable=True),
                    sa.Column('temp_path', sa.Text(), nullable=True),
                    sa.Column('source_scope', sa.String(
                        length=32), nullable=False),
                    sa.Column('document_type', sa.String(
                        length=64), nullable=True),
                    sa.Column('topic', sa.String(length=255), nullable=True),
                    sa.Column('version', sa.String(length=64), nullable=True),
                    sa.Column('effective_date', sa.Date(), nullable=True),
                    sa.Column('expiry_date', sa.Date(), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('uploaded_by', sa.UUID(), nullable=False),
                    sa.Column('processing_error', sa.Text(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_documents_document_type', 'documents',
                    ['document_type'], unique=False)
    op.create_index('ix_documents_source_scope', 'documents',
                    ['source_scope'], unique=False)
    op.create_index('ix_documents_status', 'documents',
                    ['status'], unique=False)
    op.create_index('ix_documents_topic', 'documents', ['topic'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents',
                    ['uploaded_by'], unique=False)
    op.create_table('knowledge_objects',
                    sa.Column('site_ids', postgresql.ARRAY(
                        sa.UUID()), nullable=True),
                    sa.Column('source_type', sa.String(
                        length=64), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=True),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('topic', sa.String(length=255), nullable=True),
                    sa.Column('task_type', sa.String(
                        length=128), nullable=True),
                    sa.Column('asset_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('risk_level', sa.String(
                        length=32), nullable=True),
                    sa.Column('problem', sa.Text(), nullable=True),
                    sa.Column('root_cause', sa.Text(), nullable=True),
                    sa.Column('recommended_action', sa.Text(), nullable=True),
                    sa.Column('lesson_learned', sa.Text(), nullable=True),
                    sa.Column('safety_warning', sa.Text(), nullable=True),
                    sa.Column('required_ppe', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('stop_work_triggers', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('confidence_score', sa.Numeric(
                        precision=4, scale=3), nullable=True),
                    sa.Column('sme_notes', sa.Text(), nullable=True),
                    sa.Column('rejection_reason', sa.Text(), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('approved_by', sa.UUID(), nullable=True),
                    sa.Column('approved_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_knowledge_objects_created_by',
                    'knowledge_objects', ['created_by'], unique=False)
    op.create_index('ix_knowledge_objects_risk_level',
                    'knowledge_objects', ['risk_level'], unique=False)
    op.create_index('ix_knowledge_objects_source_id',
                    'knowledge_objects', ['source_id'], unique=False)
    op.create_index('ix_knowledge_objects_source_type',
                    'knowledge_objects', ['source_type'], unique=False)
    op.create_index('ix_knowledge_objects_status',
                    'knowledge_objects', ['status'], unique=False)
    op.create_index('ix_knowledge_objects_task_type',
                    'knowledge_objects', ['task_type'], unique=False)
    op.create_index('ix_knowledge_objects_topic',
                    'knowledge_objects', ['topic'], unique=False)
    op.create_table('tokens',
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('type', sa.String(length=32), nullable=False),
                    sa.Column('token', sa.String(length=512), nullable=False),
                    sa.Column('blacklisted', sa.Boolean(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.create_table('document_sites',
                    sa.Column('document_id', sa.UUID(), nullable=False),
                    sa.Column('site_id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['site_id'], ['sites.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('document_id', 'site_id'),
                    sa.UniqueConstraint('document_id', 'site_id',
                                        name='uq_document_sites_document_id_site_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_sites')
    op.drop_table('tokens')
    op.drop_index('ix_knowledge_objects_topic', table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_task_type',
                  table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_status',
                  table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_source_type',
                  table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_source_id',
                  table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_risk_level',
                  table_name='knowledge_objects')
    op.drop_index('ix_knowledge_objects_created_by',
                  table_name='knowledge_objects')
    op.drop_table('knowledge_objects')
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_documents_topic', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_source_scope', table_name='documents')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_index('ix_sites_tenant_id', table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_knowledge_chunks_topic', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_task_type',
                  table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_status', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_source_type',
                  table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_source_scope',
                  table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_source_id',
                  table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_risk_level',
                  table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks',
                  postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_chunks')
    op.drop_table('tenants')
    op.drop_table('roles')
    # ### end Alembic commands ###
