"""show media

Revision ID: afd46c060122
Revises: 18a4b4d8f4d5
Create Date: 2026-06-04 11:19:53.477915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd46c060122'
down_revision: Union[str, None] = '18a4b4d8f4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column(
        'image_key', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column(
        'image_file_name', sa.String(length=255), nullable=True))
    op.add_column('chat_messages', sa.Column(
        'image_content_type', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column(
        'image_size_kb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'image_size_kb')
    op.drop_column('chat_messages', 'image_content_type')
    op.drop_column('chat_messages', 'image_file_name')
    op.drop_column('chat_messages', 'image_key')
    # ### end Alembic commands ###
