"""chat_table

Revision ID: faaebe060a6b
Revises: 6193f4e2b927
Create Date: 2026-06-03 17:51:03.537382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faaebe060a6b'
down_revision: Union[str, None] = '6193f4e2b927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
                    sa.Column('site_id', sa.UUID(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('mode', sa.String(length=64), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_chat_sessions_mode',
                    'chat_sessions', ['mode'], unique=False)
    op.create_index('ix_chat_sessions_site_id',
                    'chat_sessions', ['site_id'], unique=False)
    op.create_index('ix_chat_sessions_status',
                    'chat_sessions', ['status'], unique=False)
    op.create_index('ix_chat_sessions_user_id',
                    'chat_sessions', ['user_id'], unique=False)
    op.create_table('incidents',
                    sa.Column('site_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('incident_type', sa.String(
                        length=64), nullable=True),
                    sa.Column('task_type', sa.String(
                        length=128), nullable=True),
                    sa.Column('asset_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('severity', sa.String(length=32), nullable=True),
                    sa.Column('occurred_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('reported_by', sa.UUID(), nullable=False),
                    sa.Column('root_cause', sa.Text(), nullable=True),
                    sa.Column('corrective_action', sa.Text(), nullable=True),
                    sa.Column('lessons_learned', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_incidents_incident_type', 'incidents',
                    ['incident_type'], unique=False)
    op.create_index('ix_incidents_severity', 'incidents',
                    ['severity'], unique=False)
    op.create_index('ix_incidents_site_id', 'incidents',
                    ['site_id'], unique=False)
    op.create_index('ix_incidents_status', 'incidents',
                    ['status'], unique=False)
    op.create_index('ix_incidents_task_type', 'incidents',
                    ['task_type'], unique=False)
    op.create_table('chat_messages',
                    sa.Column('chat_session_id', sa.UUID(), nullable=False),
                    sa.Column('site_id', sa.UUID(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('role', sa.String(length=32), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('message_type', sa.String(
                        length=32), nullable=False),
                    sa.Column('confidence_score', sa.Numeric(
                        precision=4, scale=3), nullable=True),
                    sa.Column('rag_metadata', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_session_id'], [
                                            'chat_sessions.id'], ),
                    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_chat_messages_chat_session_id',
                    'chat_messages', ['chat_session_id'], unique=False)
    op.create_index('ix_chat_messages_message_type',
                    'chat_messages', ['message_type'], unique=False)
    op.create_index('ix_chat_messages_role',
                    'chat_messages', ['role'], unique=False)
    op.create_index('ix_chat_messages_site_id',
                    'chat_messages', ['site_id'], unique=False)
    op.create_index('ix_chat_messages_user_id',
                    'chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_sites_document_id_site_id',
                       'document_sites', type_='unique')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_site_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_role', table_name='chat_messages')
    op.drop_index('ix_chat_messages_message_type', table_name='chat_messages')
    op.drop_index('ix_chat_messages_chat_session_id',
                  table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_incidents_task_type', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_site_id', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_incident_type', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_status', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_site_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_mode', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
